name: 'Deploy OKE Infrastructure'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      # This step securely writes the private key from secrets to a temporary file
      # that both the backend and the provider can use for authentication.
      - name: 'Write OCI private key to file'
        run: |
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > /tmp/oci_api_key.pem
          chmod 600 /tmp/oci_api_key.pem

      # The 'terraform init' step uses OCI CLI environment variables for authentication
      # to connect to the remote state bucket.
      - name: 'Terraform Init'
        id: init
        env:
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_FILE: /tmp/oci_api_key.pem
          OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.OCI_STATE_BUCKET }}" \
            -backend-config="key=oke-cluster/terraform.tfstate" \
            -backend-config="compartment_id=${{ secrets.OCI_COMPARTMENT_OCID }}" \
            -backend-config="region=${{ secrets.OCI_REGION }}"

      # The 'terraform apply' step uses TF_VAR_ environment variables to pass values
      # to the variables defined in your main.tf file.
      - name: 'Terraform Apply'
        id: apply
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
          TF_VAR_user_ocid: ${{ secrets.OCI_CLI_USER }}
          TF_VAR_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          TF_VAR_private_key_path: /tmp/oci_api_key.pem
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
        run: terraform apply -auto-approve
